### ISSUE TITLE
Tempoross to-do list

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wise-old-man#705]
Essentially this PR #598 but without some of the migration changes

## API: 
- [x]  Add `temporossKills` and `temporossRank` columns to `hiscoresValues.model.ts`
- [x]  Add `tempoross` column to `delta.model.ts`
- [x]  Add deltas table migration
- [x]  Add initialValues table migration
- [x]  Add snapshots table migration
- [x]  Add Tempoross boss to the constants.ts file
    - [x]  Must be in the correct index, can only be determined after the hiscores change, but if Jagex does it correctly, should be between `skotizo` and `the gauntlet`
- [x]  Add kc to the `lynx_titan_hiscores.txt` file used for integration testing
- [x]  If the kills per hour are roughly determined already, add Tempoross achievements
- [x]  Add Tempoross to the EHB configs, with 0 EHB per hour

## App:
- [x]  Add Tempoross boss to `metrics.js` (in the correct index)
- [x]  Make Tempoross icons (small and medium)
- [x]  Make Tempoross competition background image

## Docs:
- [x]  Update API docs
    - [x]  snapshot/entities
    - [x]  record/entities
    - [x]  group/entities
    - [x]  deltas/entities
    - [x]  competitions/entities
    - [x]  achievements/entities

## Bot:
- [x]  Add Tempoross emoji
- [x]  Add Tempoross to the !ehb/!bosses command
